### ISSUE TITLE
可否添加LVGL例程?

### ISSUE THREAD

**Issue by DavidChouC** [Forairaaaaa/smooth_ui_toolkit_simu#2]
LGFX模拟器编译报错,说一些SDL的API不对,可能是版本问题?
改用LVGL,用EasingPath里的函数代替原来LVGL里的例如lv_anim_path_ease_in_out的动画路径
```
int32_t custom_path_function(const lv_anim_t * a)
{
  auto x = EasingPath::easeOutQuad(a->act_time);
  return x;
}
```
但是实现效果有问题,是否可以写一个LVGL例程参考一下
谢谢

**Comment by DavidChouC** [comment]
```
int32_t custom_path_function(const lv_anim_t * a)
{
  auto x = EasingPath::easeOutQuad(a->act_time);
  return x;
}
```

**Comment by Forairaaaaa** [comment]
可以参考 https://github.com/Forairaaaaa/Phoebe/blob/main/app/apps/utils/smooth_widget/smooth_widget.h

**Comment by DavidChouC** [comment]
> 可以参考 https://github.com/Forairaaaaa/Phoebe/blob/main/app/apps/utils/smooth_widget/smooth_widget.h

跑通了,多谢
